# This is a basic workflow to help you get started with Actions

name: Shellcheck

# Controls when the action will run. 
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck 
      - name: shellcheck install.sh
        run: shellcheck install.sh
